const MyData = {
    NumbersOf0To9: [['cero', 'zero'], ['uno', 'one'], ['dos', 'two'], ['tres', 'three'], ['cuatro', 'four'], ['cinco', 'five'], ['seis', 'six'], ['siete', 'seven'], ['ocho', 'eight'], ['nueve', 'nine']],
    NumbersOf10To19: [['diez', 'ten'], ['once', 'eleven'], ['doce', 'twelve'], ['trece', 'thirteen'], ['catorce', 'fourteen'], ['quince', 'fifteen'], ['dieciséis', 'sixteen'], ['diecisiete', 'seventeen'], ['dieciocho', 'eighteen'], ['diecinueve', 'nineteen']],
    NumbersOf20To29: [['veinte', 'twenty'], ['veintiuno', '21'], ['veintidos', '22'], ['veintitrés', '23'], ['veinticuatro', '24'], ['veinticinco', '25'], ['veintiseis', '26'], ['veintisiete', '27'], ['veintiocho', '28'], ['veintinueve', '29']],
    NumbersOf30Plush: [['treinta', 'thirty'], ['cuarenta', 'forty'], ['cincuenta', 'fifty'], ['sesenta', 'sixty'], ['setenta', 'seventy'], ['ochenta', 'eighty'], ['noventa', 'ninety'], ['cien', 'hundred']],
    // https://www.spanish.academy/blog/1000-most-common-spanish-words-for-beginners/
    TheEssentials: [
        ['sí', 'yes'],
        ['no', 'no'],
        ['¿entiende(s)?', 'do you understand?'],
        ['no entiendo', 'i don’t understand'],
        ['no (lo) sé', 'i don’t know'],
        ['no tengo ni idea', 'i have no idea'],
        ['no hablo español', 'i don’t speak spanish'],
        ['estoy perdido(a)', 'i’m lost']
    ],
    IntroduceYourself: [
        ['me llamo', 'my name is'],
        ['mi nombre es', 'my name is'],
        ['soy…', 'i’m…'],
        ['¿cómo te llamas?', 'what is your name?'],
        ['(yo) soy de…', 'i am from…']
    ],
    WhatIsUp: [
        ['¿cómo está usted?', 'how are you? (formal)'],
        ['¿cómo estás?', 'how are you? (informal)'],
        ['¿qué tal?', 'how are you? (informal) / what’s up?'],
        ['¿cómo te va?', 'how ‘s it going?'],
        ['¿qué haces?', 'what are you doing?'],
        ['¿qué pasa?', 'what ‘s happening?'],
    ],
    Responses: [
        ['¿y tú?', 'and you?'],
        ['muy bien', 'very well'],
        ['más o menos', 'so so'],
        ['así, así', 'so, so'],
        ['mal', 'bad'],
        ['como siempre', 'as always']
    ],
    EtiquetteWords: [
        ['¡de nada!', 'you’re welcome! / no problem!'],
        ['por favor', 'please'],
        ['¡perdon!', 'excuse me!'],
        ['¡disculpe!', 'excuse me!'],
        ['¡lo siento!', 'sorry!'],
        ['gracias', 'thank you'],
        ['salud', 'bless you']
    ],
    QuestionWords: [
        ['¿qué…?', 'what?'],
        ['¿quién…?', 'who?'],
        ['¿cuándo…?', 'when?'],
        ['¿dónde…?', 'where?'],
        ['¿por qué…?', 'why?'],
        ['¿cuál?', 'which?'],
        ['¿cómo…?', 'how?']
    ],
    SpanishPronouns: [
        ['Yo', 'I'],
        ['tú (informal)', 'you'],
        ['usted (formal)', 'you'],
        ['él', 'he'],
        ['ella', 'she'],
        ['nosotros/nosotras', 'we'],
        ['ustedes', 'you all'],
        ['ellos', 'they'],
        ['ellas(females)', 'they']
    ],
    Greetings: [
        ['hola', 'hello'],
        ['buenos días', 'good morning'],
        ['buenas tardes', 'good afternoon'],
        ['buenas noches', 'good evening / good night']
    ],
    TalkingAboutAge: [
        ['(yo) tengo … años', 'i am … years old.'],
        ['viejo/a', 'old'],
        ['joven', 'young'],
        ['de mediana edad', 'middle-aged'],
        ['juvenil', 'youthful'],
        ['nuevo/a', 'new'],
    ],
    Celebrate: [
        ['¡feliz cumpleaños!', 'happy birthday!'],
        ['¡felicitaciones!', 'congratulations!'],
        ['¡diviértete!', 'have fun!'],
        ['¡buen provecho!', 'bon appetit!'],
        ['¡bienvenidos! / ¡bienvenidas!', 'welcome!'],
        ['salud!', 'cheers!']
    ],
    SayGoodBye: [
        ['adiós', 'goodbye'],
        ['chao', 'goodbye'],
        ['hasta luego', 'see you later (most likely today)'],
        ['hasta mañana', 'see you tomorrow'],
        ['nos vemos', 'see you (informal)'],
        ['¡cuídate mucho!', 'take care!'],
        ['¡tenga un buen día!', 'have a nice day!'],
        ['¡hasta luego!', 'see you soon!'],
        ['¡buen viaje!', 'have a good trip!']
    ],
    // Time Words
    DaysOfTheWeek: [
        ['Domingo', 'Sunday'],
        ['Lunes', 'Monday'],
        ['Martes', 'Tuesday'],
        ['Miércoles', 'Wednesday'],
        ['Jueves', 'Thursday'],
        ['Viernes', 'Friday'],
        ['Sábado', 'Saturday']
    ],
    MonthsOfTheYear: [
        ['Enero', 'January'],
        ['Febrero', 'February'],
        ['Marzo', 'March'], ['Abril', 'April'],
        ['Mayo', 'May'],
        ['Junio', 'June'],
        ['Julio', 'July'],
        ['Agosto', 'August'],
        ['Septiembre', 'September'],
        ['Octubre', 'October'],
        ['Noviembre', 'November'],
        ['Diciembre', 'December']
    ],
    OtherTimeWords: [
        ['anteayer', 'day before yesterday'],
        ['ayer', 'yesterday'],
        ['el año', 'year'],
        ['el día', 'day'],
        ['el mes', 'month'],
        ['el siglo', 'century'],
        ['la hora', 'hour'],
        ['hoy', 'today'],
        ['la semana', 'week'],
        ['madrugada', 'dawn, very early in the morning'],
        ['mañana', 'tomorrow'],
        ['mañana', 'morning'],
        ['medianoche', 'midnight'],
        ['mediodia', 'noon'],
        ['el minuto', 'minute'],
        ['la noche', 'night'],
        ['el pasado mañana', 'day after tomorrow'],
        ['los segundos', 'seconds'],
        ['la tarde', 'afternoon']
    ],
    // Family Words
    NuclearFamily: [
        ['el padre', 'father'],
        ['el papá', 'dad'],
        ['la madre', 'mother'],
        ['la mamá', 'mom'],
        ['el hermano', 'brother'],
        ['la hermana', 'sister'],
        ['el hijo', 'son'],
        ['la hija', 'daughter'],
        ['la familia cercana', 'close family']
    ],
    ExtendedFamily: [
        ['el abuelo', 'grandfather'],
        ['la abuela', 'grandmother'],
        ['el bisabuelo', 'great-grandfather'],
        ['la bisabuela', 'great-grandmother'],
        ['la nieta', 'granddaughter'],
        ['el nieto', 'grandson'],
        ['el tío', 'uncle'],
        ['la tía', 'aunt'],
        ['el tío abuelo', 'great-uncle'],
        ['la tía abuela', 'great-aunt'],
        ['el primo', 'cousin (male)'],
        ['la prima', 'cousin (female)'],
        ['mis parientes', 'my relatives']
    ],
    FamilyVerbs: [
        ['abrazar', 'to hug'],
        ['amar', 'to love'],
        ['reír', 'to laugh'],
        ['perdonar', 'to forgive']
    ],
    ActionVerbs: [
        ['empezar', ' to start'],
        ['seguir', 'to follow'],
        ['abrir', ' to open'],
        ['buscar', 'to search'],
        ['cantar', 'to sing'],
        ['cerrar', 'to close'],
        ['destruir', 'to destroy'],
        ['dormir', 'to sleep'],
        ['encontrar', 'to find'],
        ['esconder', 'to hide'],
        ['esperar', 'to wait'],
        ['faltar', 'to miss'],
        ['hacer', 'to do '],
        ['intentar', 'to try'],
        ['llamar', 'to call'],
        ['llevar', 'to take'],
        ['llorar', 'to cry'],
        ['luchar', 'to fight'],
        ['mentir', 'to lie'],
        ['odiar', 'to hate'],
        ['recibir', 'to receive'],
        ['reconocer', 'to recognize'],
        ['robar', 'to steal'],
        ['salvar', 'to save'],
        ['sonreír', 'to smile'],
        ['soñar', 'to dream'],
        ['tomar', 'to take'],
        ['Vivir', 'to live']
    ],
    // The Five Senses
    Sound: [
        ['tranquilo/a', 'quiet'],
        ['ruidoso/a', 'loud'],
        ['gritar', 'to shout'],
        ['escuchar', 'to hear'],
        ['silencio', 'silence'],
        ['alto', 'loud'],
        ['bajo', 'soft'],
        ['ensordecedor', 'deafening'],
        ['agudo', 'sharp, high-pitched'],
        ['grave', 'low-pitched'],
        ['melodioso', 'melodious'],
        ['armónico', 'harmonic'],
        ['zumbido', 'buzz'],
        ['sordo', 'deaf'],
        ['duro de oíd', 'hard of hearing'],
        ['oído fino', 'acute hearing'],
        ['problemas de audición', 'hearing-impaired'],
        ['fuera de alcance', ' out of earshot']
    ],
    Sight: [
        ['ver', 'to see'],
        ['mirar', 'to look'],
        ['de colores', 'colorful'],
        ['blanco y negro', 'black and white'],
        ['brillante', 'bright'],
        ['apagado', 'dim'],
        ['claro', 'light'],
        ['oscuro', 'dark'],
        ['ciego', 'blind'],
        ['mirar fijamente', 'to stare'],
        ['echar un vistazo', 'to glance'],
        ['bizquear', 'to squint'],
        ['guiñar', 'to wink'],
        ['parpadear', 'to blink']
    ],
    Touch: [
        ['tocar', 'to touch'],
        ['agarrar', 'to grab'],
        ['suave', 'soft'],
        ['áspero(a)', 'rough'],
        ['liso(a)', 'smooth'],
        ['rugoso(a)', 'wrinkled'],
        ['pegajoso(a)', 'sticky'],
        ['punzante', 'sharp'],
        ['sedoso(a)', 'silky'],
        ['esponjoso(a)', 'spongy'],
        ['mullido(a)', 'fluffy'],
        ['hormigueo', 'tingle'],
        ['entumecido(a)', 'numb'],
        ['rozar', 'to touch gently'],
        ['acariciar', 'to caress'],
        ['agarrar', 'to grab']
    ],
    Smell: [
        ['olor', 'smell'],
        ['el perfume', 'scent'],
        ['la fragancia', 'fragrance'],
        ['el hedor', 'stench'],
        ['apestoso(a)', 'smelly'],
        ['fresco(a) ', 'fresh'],
        ['acre', 'pungent'],
        ['húmedo(a)', 'musty'],
        ['podrido(a)', 'rotten'],
        ['ahumado(a)', 'smoky'],
        ['apestar', 'to stink']
    ],
    Taste: [
        ['gusto', 'taste'],
        ['sabor', 'flavor'],
        ['probar', 'try'],
        ['sabroso ', 'está sabrosa'],
        ['delicioso', ' delicious '],
        ['perfecto ', ' perfect'],
        ['apetitoso ', 'appetizing'],
        ['dulce ', 'sweet'],
        ['dulzón', ' sugary '],
        ['soso ', 'bland']
    ],
    // Describing Words
    Distance: [
        ['abierto/a', 'open'],
        ['ancho/a', 'wide'],
        ['estrecho/a', 'narrow'],
        ['lejano/a', 'far'],
        ['cercano/a', 'close']
    ],
    PersonalityAndEmotions: [
        ['alegre', 'joyful'],
        ['gracioso/a', 'funny, amusing'],
        ['serio/a', 'serious'],
        ['tímido/a', 'shy'],
        ['valiente', 'brave'],
        ['loco/a', 'crazy'],
        ['contento(a)', 'content'],
        ['feliz', 'happy'],
        ['preocupado(a)', 'worried'],
        ['nervioso(a)', 'nervous'],
        ['tranquilo(a)', 'tranquil'],
        ['calmado(a)', 'calm'],
        ['emocionado(a)', 'excited']
    ],
    // Physical Adjectives
    Hair: [
        ['largo/a', 'long'],
        ['corto/a', 'short'],
        ['liso/a', 'straight'],
        ['rizado/a', 'curly'],
        ['ondulado/a', 'wavy'],
        ['castaño/a', 'brown'],
        ['rubio/a', 'blonde'],
        ['pelirrojo/a', 'red'],
        ['negro/a', 'black'],
        ['canoso/a', 'grey'],
        ['abundante', 'thick'],
        ['fino/a', 'thin'],
        ['escalado/a', 'layered'],
        ['teñido/a', 'dyed'],
        ['saludable', 'healthy'],
        ['claro/a', 'light'],
        ['encrespado/a', 'frizzy'],
        ['brillante', 'shiny'],
        ['calvo/a', 'bald'],
    ],
    Size: [
        ['grande', 'big'],
        ['pequeño/a', 'small'],
        ['enorme', 'huge'],
        ['delgado/a', 'lean'],
        ['esbelto/a', 'slender'],
        ['flaco/a', 'skinny'],
        ['menudo/a', 'petite'],
        ['alto/a', 'tall'],
        ['bajo/a', 'short'],
    ],
    Looks: [
        ['hermoso/a', 'beautiful'],
        ['guapo/a', 'handsome'],
        ['feo/a', 'ugly'],
        ['adorable', 'cute'],
        ['bonita', 'pretty'],
        ['impresionante', 'stunning'],
        ['poco atractivo/a', 'plain'],
        ['promedio/a', 'average'],
        ['atractivo/a', 'attractive']
    ],
    Colors: [
        ['café', 'brown'],
        ['celeste', 'sky blue'],
        ['negro', 'black'],
        ['marrón / café', 'brown'],
        ['gris', 'grey'],
        ['blanco', 'white'],
        ['amarillo', 'yellow'],
        ['anaranjado', 'orange'],
        ['rojo', 'red'],
        ['rosado', 'pink'],
        ['morado / púrpura', 'purple'],
        ['azul', 'blue'],
        ['verde', 'green'],
    ],
    ArtsAndCrafts: [
        ['colorear', 'to color'],
        ['construir', 'to construct'],
        ['cortar', 'to cut'],
        ['coser', 'to sew'],
        ['dibujar', 'to draw'],
        ['pintar', 'to paint']
    ],
    // Numbers
    // Animals
    FarmAnimals: [
        ['el gato', 'cat'],
        ['el perro', 'dog'],
        ['el conejo', 'rabbit'],
        ['el pollo', 'chicken'],
        ['la gallina', 'hen'],
        ['el gallo', 'rooster'],
        ['la vaca', 'cow'],
        ['el toro', 'bull'],
        ['la oveja', 'sheep'],
        ['el caballo', 'horse'],
        ['el cerdo', 'pig'],
        ['la cabra', 'goat'],
        ['el burro', 'donkey'],
        ['el ratón', 'mouse']
    ],
    ForestAnimals: [
        ['el ciervo', 'deer'],
        ['el mapache', 'raccoon'],
        ['la ardilla -', 'squirrel'],
        ['el búho', 'owl'],
        ['el zorro', 'fox'],
        ['el lobo', 'wolf'],
        ['el oso', 'bear'],
    ],
    OceanAnimals: [
        ['el cangrejo', 'crab'],
        ['la medusa', 'jellyfish'],
        ['el delfín', 'dolphin'],
        ['la ballena', 'whale'],
        ['el tiburón', 'shark'],
        ['la foca', 'seal'],
        ['el lobo marino', 'sea lion'],
        ['la morsa', 'walrus'],
        ['el pingüino', 'penguin'],
    ],
    Travel: [
        ['el viaje', 'trip'],
        ['el equipaje', 'bags'],
        ['la salida', 'exit'],
        ['la llegada', 'arrival'],
        ['los documentos de identidad', 'id papers'],
        ['el billete de avión', 'boarding pass'],
        ['el hotel', 'hotel'],
        ['el permiso de conducir', 'driver'],
        ['echar gasolina', 'to get gas'],
        ['viajar', 'to travel'],
        ['volver', 'to return'],
        ['ir', 'to go'],
        ['salir', 'to leave'],
        ['parar', 'to stop'],
        ['partir', 'to depart'],
        ['porter(a)', 'doorman'],
        ['hostia', 'hostess'],
        ['botones', 'bellhop'],
        ['anfitriona', 'airline hostess'],
    ],
    Transportation: [
        ['el avión', 'airplane'],
        ['el coche', 'car'],
        ['la bicicleta', 'bicycle'],
        ['la motocicleta', 'motorcycle'],
        ['el tren', 'train'],
        ['el metro/subte', 'subway'],
        ['el autobús', 'bus'],
        ['el barco', 'ship'],
        ['taxista', 'taxi driver'],
        ['revisor(a)', 'train conductor'],
        ['dependiente de gas', 'gas station attendant'],
        ['conductor(a)', 'driver, chauffeur'],
        ['camionero(a)', 'truck driver'],
    ],
    Weather: [
        ['el sol', 'the sun'],
        ['las nubes', 'the clouds'],
        ['la niebla', 'the fog'],
        ['la neblina', 'the mist'],
        ['la lluvia', 'the rain'],
        ['la llovizna', 'the drizzle'],
        ['la tormenta', 'the storm'],
        ['el tornado', 'the tornado'],
        ['el trueno', 'the thunder'],
        ['el relámpago', 'the lightning strike'],
        ['el rayo', 'the lightning bolt'],
        ['el viento', 'the wind'],
        ['la brisa', 'the breeze'],
        ['el granizo', 'the hail'],
        ['el hielo', 'the ice'],
        ['la nieve', 'the snow'],
        ['el calor', 'the heat'],
        ['el frío', 'the cold'],
        ['la humedad', 'the humidity'],
        ['la temperatura', 'the temperature'],
        ['el pronóstico', 'the forecast'],
    ],
    WeatherVerbs: [
        ['llover', 'to rain'],
        ['lloviznar', 'to drizzle'],
        ['diluviar', 'to pour down'],
        ['granizar', 'to hail'],
        ['nevar', 'to snow'],
    ],
    Seasons: [
        ['el invierno', 'winter'],
        ['la primavera', 'spring'],
        ['el verano', 'summer'],
        ['el otoño', 'fall'],
    ],
    Business: [
        ['carta de motivación', 'cover letter'],
        ['el cv', 'resume'],
        ['la firma', 'firm'],
        ['el negocio', 'business'],
        ['la compañía', 'company'],
        ['el jefe', 'boss'],
        ['el empleado', 'employee'],
        ['trabajar', 'to work'],
        ['negociar', 'to negotiate'],
        ['consultor(a)', 'consultant'],
        ['dueño(a)', 'owner'],
    ],
    Careers: [
        ['abogado(a)', 'lawyer'],
        ['arquitecto(a)', 'architect'],
        ['bombero(a)', 'fireman'],
        ['campesino(a)', 'farm worker'],
        ['carpintero(a)', 'carpenter'],
        ['cartero(a)', 'postal worker'],
        ['casero(a)', 'landlord'],
        ['científico(a)', 'scientist'],
        ['cocinero(a)', 'cook, chef'],
        ['consejero (a)', 'counselor'],
        ['constructor (a)', 'construction worker'],
        ['contador(a)', 'accountant/bookkeeper'],
        ['doméstico(a)', 'maid'],
        ['detective', 'detective'],
        ['director, revisor, redactor(a)', 'editor'],
        ['electricista', 'electrician'],
        ['escritor / autor(a)', 'writer / author'],
        ['vaquero, tropero(a)', 'cowboy'],
        ['manejador(a)', 'manager'],
        ['granjero(a)', 'farmer'],
        ['ingeniero(a)', 'engineer'],
        ['jardinero(a)', 'gardener'],
        ['jefe', 'boss'],
        ['juez', 'judge'],
        ['lavandero(a)', 'laundry person'],
        ['marinero(a)', 'merchant marine'],
        ['mecánico (a)', 'mechanic'],
        ['camarero(a)', 'waiter'],
        ['padre', 'priest'],
        ['panadero(a)', 'baker'],
        ['pastor(a)', 'pastor/minister'],
        ['periodista', 'reporter/journalist'],
        ['pescador(a)', 'fisherman'],
        ['pintor(a)', 'painter'],
        ['plomero(a)', 'plumber'],
        ['Policía', 'policeman'],
        ['programador(a)', 'computer programmer'],
        ['dueño(a)', 'owner'],
        ['químico(a)', 'chemist'],
        ['ranchero(a)', 'rancher'],
        ['rebuscador(a)', 'researcher'],
        ['reparador(a)', 'repairman'],
        ['técnico(a) de laboratorio', 'lab technician'],
        ['trabajador(a) de fábrica', 'factory worker'],
        ['veterinario(a)', 'veterinarian'],
    ],
    Sports: [
        ['ir al gimnasio', 'go to the gym'],
        ['ir de caminata', 'go hiking'],
        ['levantar pesas', 'lift weight'],
        ['mantenerse en forma', 'to stay in shape'],
        ['practicar', 'to practice'],
        ['nadar', 'to swim'],
        ['el yoga', 'yoga'],
        ['el fútbol', 'soccer'],
        ['el fútbol americano', 'football'],
        ['el béisbol', 'baseball'],
        ['el baloncesto', 'basketball'],
        ['el golf', 'golf'],
        ['el hockey', 'hockey'],
        ['el tenis', 'tennis'],
        ['el voleibol', 'volleyball'],
        ['luchar', 'to wrestle/to fight'],
        ['correr', 'to run'],
        ['esquiar', 'to ski'],
        ['el partido', 'game/match'],
        ['la carrera', 'race'],
        ['el torneo', 'tournament'],
    ],
    SportsVerbs: [
        ['patear', 'to kick'],
        ['saltar', 'to jump'],
        ['parar', 'to stop/to block'],
        ['balancear', 'to swing'],
        ['servir', 'to serve'],
        ['rematar', 'to spike'],
        ['pegar', 'to hit'],
        ['driblar', 'to dribble'],
        ['tirar', 'to throw'],
        ['agarrar', 'to catch'],
        ['ganar', 'to win'],
        ['perder', 'to lose'],
        ['empatar', 'to tie'],
        ['caminar', 'to walk'],
        ['bailar', 'to dance'],
        ['jugar', 'to play'],
        ['competir', 'to compete'],
    ],
    // Time to Eat!
    FoodAndDrink: [
        ['la comida', 'food'],
        ['las bebidas', 'drinks'],
        ['las verduras', 'vegetables'],
        ['las frutas', 'fruits'],
        ['cocinar', 'to cook'],
        ['tengo hambre', 'i'],
        ['tengo sed', 'i'],
    ],
    Meats: [
        ['la res', 'beef'],
        ['el pollo', 'chicken'],
        ['la gallina', 'chicken'],
        ['el cordero', 'lamb'],
        ['la barbacoa', 'grilled'],
        ['el cerdo', 'pork'],
        ['el perrito caliente', 'hot dog'],
        ['el jamón', 'ham'],
        ['la hamburguesa', 'hamburger'],
        ['el tocino', 'bacon'],
        ['el pescado', 'fish'],
    ],
    Vegetables: [
        ['la zanahoria', 'carrot'],
        ['la lechuga', 'lettuce'],
        ['el tomate', 'tomato'],
        ['la maíz', 'corn'],
        ['la papa', 'potato'],
        ['la patata', 'potato'],
        ['las papas', 'french fries'],
        ['las patatas fritas', 'french fries'],
        ['el brocoli', 'broccoli'],
        ['la espinaca', 'spinach'],
        ['la cebolla', 'onion'],
        ['la col', 'cabbage'],
        ['la ensalada', 'salad'],
        ['la aceituna', 'olive'],
        ['las calabacitas', 'squash'],
        ['el hongo', 'mushroom'],
        ['el pepino', 'cucumber'],
    ],
    Fruits: [
        ['la manzana', 'apple'],
        ['la pera', 'pear'],
        ['la fresa', 'strawberry'],
        ['la frambuesa', 'raspberry'],
        ['la zarzamora', 'blackberry'],
        ['el arándano', 'blueberry'],
        ['el arándano rojo', 'cranberry'],
        ['la naranja', 'orange'],
        ['la mandarina', 'tangerine'],
        ['la toronja', 'grapefruit'],
        ['el limón', 'lemon'],
        ['la lima', 'lime'],
        ['el plátano', 'banana'],
        ['la piña', 'pineapple'],
        ['el coco', 'coconut'],
        ['el mango', 'mango'],
        ['la papaya', 'papaya'],
    ],
    Drinks: [
        ['la cerveza', 'beer'],
        ['el refresco', 'pop, soft drink'],
        ['el té', 'tea'],
        ['el té helado', 'iced tea'],
        ['el café', 'coffee'],
        ['la leche', 'milk'],
        ['el agua', 'water'],
        ['el jugo', 'juice'],
        ['el batido', 'milkshake'],
    ],
    Desserts: [
        ['el chocolate', 'chocolate'],
        ['los dulces', 'candy'],
        ['el pastel', 'cake'],
        ['las galletas', 'cookies'],
        ['el helado', 'ice cream'],
        ['el churros con chocolate', 'chocolate churros'],
        ['el basque cheesecake', 'cheesecake'],
    ],
    Utensils: [
        ['el plato', 'plate'],
        ['el plato hondo', 'bowl'],
        ['el vaso', 'glass'],
        ['la copa', 'cup'],
        ['el tenedor', 'fork'],
        ['la cuchara', 'spoon'],
        ['el cuchillo', 'knife'],
        ['la servilleta', 'napkin'],
    ],
    Taste: [
        ['dulce', 'sweet'],
        ['salado(a)', 'savory'],
        ['rico(a)', 'delicious'],
    ],
    Meals: [
        ['el desayuno', 'breakfast'],
        ['el almuerzo', 'lunch'],
        ['la cena', 'dinner'],
        ['el tentempié', 'snack'],
    ],
    Clothing: [
        ['la prenda, la ropa', 'clothes'],
        ['los zapatos', 'shoes'],
        ['el pantalón', 'pants'],
        ['la camiseta / la camisa', 'shirt'],
        ['la chaqueta', 'jacket'],
        ['la falda', 'skirt'],
        ['el suéter', 'sweater'],
        ['el vestido', 'dress'],
    ],
    HolidaysAndParties: [
        ['la navidad', 'christmas'],
        ['el año nuevo', 'new year'],
        ['la pascua', 'easter'],
        ['el día de san valentín', 'valentine'],
        ['el día de la madre', 'mother'],
        ['el día del padre', 'father'],
        ['el día de la independencia', 'independence day'],
        ['el día de acción de gracias', 'thanksgiving'],
        ['el cumpleaños', 'birthday'],
        ['la fiesta', 'the party'],
        ['la boda', 'the wedding'],
    ],
    PartsOfTheBody: [
        ['el cuerpo humano', 'the human body'],
        ['la cabeza', 'head'],
        ['el pecho', 'chest'],
        ['el oído / la oreja', 'ear'],
        ['el ojo', 'eye'],
        ['la cara', 'face'],
        ['la mano', 'hand'],
        ['la boca', 'mouth'],
        ['el pie', 'foot'],
        ['la espalda', 'back'],
        ['el pelo', 'hair'],
        ['el codo', 'elbow'],
        ['el dedo', 'finger'],
        ['la pantorrilla', 'calf'],
        ['la pierna', 'leg'],
        ['la muñeca', 'wrist'],
        ['el talón', 'heel'],
        ['el brazo', 'arm'],
        ['el cuello', 'neck'],
        ['el tobillo', 'ankle'],
        ['la frente', 'forehead'],
        ['el muslo', 'thigh'],
        ['la barba', 'beard'],
        ['el bigote', 'mustache'],
        ['la lengua', 'tongue'],
        ['el dedo del pie', 'toe'],
        ['la cintura', 'waist'],
        ['la cadera', 'hip'],
        ['las nalgas', 'buttocks'],
        ['el pulgar', 'thumb'],
        ['la rodilla', 'knee'],
        ['la nariz', 'nose'],
        ['la mejilla, el cachete', 'cheek'],
        ['los labios', 'lips'],
        ['el hombro', 'shoulder'],
        ['la barbilla, el mentón', 'chin'],
        ['las cejas', 'eyebrows'],
        ['las pestañas', 'eyelashes'],
        ['el ombligo', 'belly button'],
        ['la piel', 'skin'],
        ['el vientre', 'stomach'],
        ['la garganta', 'throat'],
        ['los dientes/las muelas', 'teeth'],
    ],
    // Transition Words
    TimeAndPlace: [
        ['al principio', 'at the beginning'],
        ['en primer lugar', 'firstly'],
        ['para comenzar', 'to start'],
        ['antes', 'before'],
        ['después', 'after'],
        ['a continuación', 'in continuation'],
        ['mientras tanto', 'meanwhile'],
        ['al final', 'at the end'],
    ],
    AddAnIdea: [
        ['además', 'additionally'],
        ['aparte de', 'apart from'],
        ['asimismo', 'at the same time'],
        ['también', 'also'],
        ['de igual manera', 'in the same way'],
    ],
    CompareContrast: [
        ['pero', 'but'],
        ['sin embargo', 'however'],
        ['no obstante', 'nevertheless'],
        ['por otro lado', 'on the other hand'],
        ['aunque', 'even though'],
        ['a pesar de', 'despite'],
    ],
    // Location Words
    Prepositions: [
        ['dentro de', 'inside of'],
        ['encima de/sobre', 'on top of'],
        ['debajo de', 'underneath of'],
        ['delante de', 'in front of'],
        ['detrás de', 'behind'],
        ['entre', 'between'],
        ['en', 'in/on/at'],
        ['dentro de', 'inside of'],
        ['fuera de', 'outside of'],
        ['arriba de', 'above'],
        ['en medio de', 'in the middle of'],
        ['cerca de', 'close to'],
        ['lejos de', 'far from'],
        ['al lado de', 'next to'],
        ['alrededor de', 'around'],
        ['a la izquierda de', 'to the left of'],
        ['a la derecha de', 'to the right of'],
    ],
    LocationVerbs: [
        ['estar', 'to be'],
        ['colocar', 'to place'],
        ['ubicar', 'to position'],
        ['poner', 'to put'],
        ['situar', 'to place'],
    ],
    HereAndThere: [
        ['aquí, acá', 'here'],
        ['ahí', 'there'],
        ['allí', 'there'],
        ['allá', 'over there'],
    ],
    Directions: [
        ['el este', 'east'],
        ['el norte', 'north'],
        ['el oeste', 'west'],
        ['el sur', 'south'],
    ],
    // School
    ClassroomObjects: [
        ['la clase', 'classroom'],
        ['el aula', 'classroom'],
        ['la pizarra', 'blackboard'],
        ['el pizarrón', 'whiteboard'],
        ['la tiza', 'chalk'],
        ['el marcador', 'marker'],
        ['el borrador', 'eraser'],
        ['el escritorio', 'desk'],
        ['el pupitre', 'desk'],
        ['la silla', 'chair'],
        ['la mochila', 'backpack'],
        ['el libro', 'book'],
        ['el cuaderno', 'notebook'],
        ['el papel', 'paper'],
        ['el lápiz', 'pencil'],
        ['los lápices de colores', 'coloring pencils'],
        ['el sacapuntas', 'pencil sharpener'],
        ['el bolígrafo', 'pen'],
        ['la goma', 'eraser'],
        ['las tijeras', 'scissors'],
        ['la cola/el pegamento', 'glue'],
        ['la regla', 'ruler'],
        ['la grapadora', 'stapler'],
        ['el estuche', 'pencil case'],
    ],
    ClassroomActivities: [
        ['estudiar', 'to study'],
        ['repasar', 'to revise'],
        ['aprender', 'to learn'],
        ['saber', 'to know'],
        ['hacer los deberes', 'to do homework'],
        ['hacer la tarea', 'to do homework'],
        ['leer', 'to read'],
        ['escribir', 'to write'],
        ['hablar', 'to speak'],
        ['decir', 'to say'],
        ['preguntar', 'to ask'],
        ['charlar', 'to chat'],
        ['dictar', 'to dictate'],
        ['deletrear', 'to spell'],
        ['contar', 'to count'],
        ['faltar', 'to miss school'],
        ['aprobar', 'to pass a subject/a test'],
        ['reprobar', 'to fail a subject/a test'],
        ['prestar', 'to lend'],
        ['tomar prestado', 'to borrow'],
        ['traer', 'to bring'],
        ['enseñar', 'to teach'],
        ['mostrar', 'to show'],
        ['nombrar', 'to name'],
        ['ayudar', 'to help'],
    ],
    PlacesInASchool: [
        ['la escuela', 'school'],
        ['el colegio', 'school'],
        ['el gimnasio', 'gym'],
        ['el patio', 'playground'],
        ['el baño', 'restroom'],
        ['el pasillo', 'hallway'],
        ['la biblioteca', 'library'],
        ['la oficina', 'office'],
        ['la sala de profesores', 'staff room'],
        ['el comedor', 'cafeteria'],
        ['la cocina', 'kitchen'],
        ['la enfermería', 'infirmary'],
        ['el laboratorio', 'lab'],
    ],
    PeopleInASchool: [
        ['maestro/a', 'teacher (primary school)'],
        ['profesor/a', 'teacher (secondary school)'],
        ['entrenador/a', 'coach'],
        ['enfermero/a', 'nurse'],
        ['director/a', 'principal'],
        ['alumno/a', 'student'],
        ['estudiante', 'student'],
    ],
    MoreSchoolWords: [
        ['el almuerzo', 'lunch'],
        ['el recreo', 'recess'],
        ['las vacaciones', 'vacations'],
        ['la comida', 'food'],
        ['el casillero', 'locker'],
        ['la materia', 'subject'],
        ['la matemática', 'math'],
        ['la biología', 'biology'],
        ['la química', 'chemistry'],
        ['la física', 'physics'],
        ['la educación física', 'physical education'],
        ['la historia', 'history'],
        ['la literatura', 'literature'],
        ['la prueba', 'test'],
        ['el examen', 'exam'],
        ['la nota', 'grade'],
        ['la calificación', 'grade'],
    ],
    Technology: [
        ['un ordenador (Spain)', 'a computer'],
        ['una computadora (Latin America)', 'a computer'],
        ['una tableta', 'a tablet'],
        ['una impresora', 'a printer'],
        ['el ratón', 'the mouse'],
        ['apagar', 'to turn on'],
        ['encender', 'to turn off'],
        ['el disco duro', 'the hard drive'],
        ['el teclado', 'the keyboard'],
        ['la tecla', 'the key'],
        ['los auriculares', 'headphones'],
        ['el micrófono', 'the mic'],
        ['la pantalla', 'the screen'],
        ['la cámara', 'the camera'],
        ['los altavoces', 'the speakers'],
        ['una aplicación', 'an app'],
        ['base de datos', 'database'],
        ['las redes sociales', 'social networks'],
        ['el enlace', 'the link'],
        ['subir', 'to upload'],
        ['guardar', 'to save'],
        ['borrar', 'to delete'],
        ['hacer click', 'to click'],
        ['bajar/descargar', 'to download'],
        ['buscar en Google', 'search on Google'],
        ['pirata informático', 'hacker'],
        ['contraseña', 'password'],
    ],
    HomeSweetHome: [
        ['la casa', 'house, home'],
        ['el hogar', 'home'],
        ['la habitación', 'bedroom'],
        ['el cuarto', 'bedroom'],
        ['el dormitorio', 'bedroom'],
        ['la sala', 'living room'],
        ['el comedor', 'dining room'],
        ['la cocina', 'kitchen'],
        ['el baño', 'bathroom'],
        ['el pasillo', 'hallway'],
        ['el jardín', 'yard, garden'],
        ['el garaje', 'garage'],
        ['cómodo/a', 'comfortable'],
        ['acogedor', 'cozy'],
        ['desordenado/a', 'messy'],
        ['limpio/a', 'clean'],
    ],
    Bathroom: [
        ['la pasta de dientes', 'toothpaste'],
        ['el cepillo de dientes', 'toothbrush'],
        ['el jabón', 'soap'],
        ['el secador de pelo', 'hair dryer'],
        ['el champú', 'shampoo'],
        ['el cepillo', 'brush'],
        ['el papel higiénico', 'toilet paper'],
        ['la toalla', 'towel'],
        ['el agua jabonosa', 'soapy water'],
        ['la bolsa de basura', 'trash bag'],
        ['el cubo de basura', 'trash can'],
        ['el cesto de la ropa sucia', 'laundry basket'],
        ['la navaja de afeitar', 'razor'],
        ['la maquinilla de afeitar eléctrica', 'electric razor'],
        ['la crema de afeitar', 'shaving cream'],
        ['el enjuague bucal', 'mouthwash'],
        ['el cepillo de pelo', 'hair brush'],
        ['el peine', 'comb'],
        ['el limpiador facial', 'facial cleanser'],
        ['la balanza', 'scale'],
        ['el pañuelo de papel', 'tissue'],
        ['los juguetes de baño', 'bath toys'],
        ['la alfombra de baño', 'bath mat'],
        ['la ducha', 'shower'],
        ['la bañera', 'bathtub'],
        ['el fregadero', 'sink'],
        ['el inodoro', 'toilet'],
        ['el grifo', 'faucet'],
        ['el espejo', 'mirror'],
        ['peinar', 'to comb'],
    ],
    KitchenVerbs: [
        ['cocinar', 'to cook'],
        ['comer', 'to eat'],
        ['adobar', 'to marinate'],
        ['sazonar', 'to season'],
        ['lavar', 'to wash'],
        ['cortar', 'to cut'],
        ['pelar', 'to peel'],
        ['picar', 'to chop'],
        ['moler', 'to grind'],
        ['incorporar', 'to add'],
        ['mezclar', 'to mix'],
        ['catir', 'to whisk'],
        ['licuar', 'to blend'],
        ['combinar', 'to combine'],
        ['freír', 'to fry'],
        ['hervir', 'to boil'],
        ['colar', 'to strain'],
        ['cocer', 'to cook'],
        ['hornear', 'to bake'],
        ['asar', 'to grill / roast'],
        ['saltear', 'to saute'],
        ['preparar', 'to prepare'],
        ['descongelar', 'to defrost'],
        ['quemar', 'to burn'],
        ['tostar', 'to toast'],
        ['derretir', 'to melt'],
        ['rodajear', 'to slice'],
        ['calentar', 'to warm up / heat'],
        ['rellenar', 'to fill / stuff'],
        ['lavar', 'to wash'],
        ['limpiar', 'to clean'],
        ['desayunar', 'to have breakfast'],
        ['cenar', 'to have dinner'],
    ],
    Bedroom: [
        ['la puerta', 'the door'],
        ['el armario', 'the wardrobe'],
        ['la estantería', 'the shelf'],
        ['la ventana', 'the window'],
        ['las cortinas', 'the curtains'],
        ['el escritorio', 'the desk'],
        ['el ordenador', 'the computer'],
        ['la cama', 'the bed'],
        ['el cojín', 'the pillow'],
        ['el edredón', 'the quilt'],
        ['las sábanas', 'the bedding'],
        ['la almohada', 'the pillowcase'],
        ['la lámpara', 'the lamp'],
        ['la mesilla de noche', 'the night table or nightstand'],
        ['el espejo', 'the mirror'],
        ['el cuadro', 'the painting'],
    ],
    LivingRoom: [
        ['la puerta', 'the door'],
        ['el armario', 'the wardrobe'],
        ['la estantería', 'the shelf'],
        ['la ventana', 'the window'],
        ['las cortinas', 'the curtains'],
        ['la mesa', 'the table'],
        ['la silla', 'the chair'],
        ['el sillón', 'armchair'],
        ['la alfombra', 'the carpet or rug'],
        ['la lámpara', 'the lamp'],
        ['la planta', 'the plant'],
        ['las flores', 'the flowers'],
        ['la chimenea', 'the chimney'],
        ['el suelo', 'the ground'],
        ['el techo', 'the ceiling'],
    ],
    Shopping: [
        ['dependiente/a', 'shop assistant'],
        ['caja', 'checkout'],
        ['rebajas', 'sales'],
        ['ocasión', 'bargain'],
        ['recibo', 'receipt'],
        ['probadores', 'dressing room'],
        ['tamaño', 'size'],
        ['tienda de ropa', 'clothing store'],
        ['zapatería', 'shoe store'],
        ['librería', 'bookstore'],
        ['almacén', 'department store'],
        ['supermercado', 'supermarket'],
        ['joyería', 'jeweler'],
        ['juguetería', 'toy store'],
        ['almacenero(a)', 'grocer'],
        ['comerciante (a)', 'merchant'],
        ['tendero(a)', 'shopkeeper'],
        ['dependiente', 'clerk'],
        ['cajero(a)', 'cashier'],
    ],
    // Talk About Your Health in Spanish
    HealthcareProfessionals: [
        ['los cuidados de la salud', 'healthcare'],
        ['el dentista', 'dentist'],
        ['el doctor/a', 'doctor'],
        ['el enfermero/a', 'nurse'],
        ['el médico general', 'general practitioner'],
        ['el médico de cabecera', 'general practitioner'],
        ['el médico especialista', 'specialist'],
        ['el/la nutricionista', 'nutritionist'],
        ['el/la paciente', 'patient'],
        ['el/la paramédico', 'paramedic'],
        ['quiropráctico(a)', 'chiropractor'],
        ['el/la pediatra', 'pediatrician'],
        ['el psicólogo/a', 'psychologist'],
        ['los primeros auxilios', 'first aid'],
        ['la salud', 'health'],
    ],
    HealthcareServices: [
        ['la ambulancia', 'ambulance'],
        ['la aseguradora', 'insurance carrier'],
        ['el centro de salud', 'clinic'],
        ['la clínica', 'clinic'],
        ['la farmacia', 'drug store'],
        ['droguería', 'drug store'],
        ['el hospital', 'hospital'],
        ['el pabellón', 'ward'],
        ['la sala de espera', 'waiting room'],
        ['la sala de operaciones', 'operating room'],
        ['el sanatorio', 'sanatorium'],
    ],
    IllnessesAndInjuries: [
        ['la alergía', 'allergy'],
        ['la  asfixia', 'suffocation'],
        ['el asma', 'asthma'],
        ['el ataque al corazón/paro cardiaco', 'heart attack'],
        ['el calambre', 'muscle cramp'],
        ['el cancer', 'cancer'],
        ['el chinchón', 'head bump'],
        ['el corte', 'cut'],
        ['la deshidratación', 'dehydration'],
        ['la diabetes', 'diabetes'],
        ['la diarrea', 'diarrhea'],
        ['el dolor', 'ache/pain'],
        ['el dolor de cabeza', 'headache'],
        ['el dolor de garganta', 'sore throat'],
        ['el dolor de estómago', 'stomach ache'],
        ['el dolor de diente', 'toothache'],
        ['la enfermedad', 'disease'],
        ['la enfermedad cardiaca', 'heart disease'],
        ['la enfermedad infecciosa', 'infectious disease'],
        ['los escalofríos', 'shaking chills'],
        ['la fractura', 'fracture'],
        ['la fiebre', 'fever'],
        ['la gripe', 'flu'],
        ['la herida', 'wound'],
        ['la hipotermia', 'hypothermia'],
        ['la infección', 'infection'],
        ['el malestar', 'discomfort'],
        ['el morete/moretón', 'bruise'],
        ['la náusea', 'nausea'],
        ['el raspón', 'graze'],
        ['el resfriado', 'cold'],
        ['el sangrado', 'bleeding'],
        ['la tos', 'cough'],
        ['el virus', 'virus'],
        ['el vomito', 'vomit'],
    ]




}